#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 25 13:39:45 2018

@author: JovaniSenpai
"""

import numpy as np

#M = ['0,2', [1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

R1 = np.r_[1,2,3,4,5]